gateways:
  local:
    connection:
      type: motherduck
      database: adriano_warehouse
      token: { { env_var('motherduck_token') } }

default_gateway: local

model_defaults:
  dialect: duckdb
  start: 2025-02-20
